import React, { Suspense, useRef } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { gsap } from 'gsap'
import { Canvas } from '@react-three/fiber'
import { OrbitControls, Stage } from '@react-three/drei'
import Duck from '../components/models/Duck'

const Home: NextPage = () => {
  const textRef = React.useRef<HTMLDivElement>(null)
  const duckRef = React.useRef<any>(null);

  React.useEffect(() => {
    gsap.to(textRef.current, { rotation: '+=360', repeat: -1 })
  })

  return (
    <div>
      <Head>
        <title>1tpp | Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen w-full">

        <Canvas shadows dpr={[1, 2]} camera={{ fov: 50 }}>
          <Suspense fallback={null}>
            <Stage
              controls={duckRef}
              preset="rembrandt"
              intensity={1}
              environment="city"
            >
              <Duck />
            </Stage>
          </Suspense>
          <OrbitControls ref={duckRef} autoRotate />
        </Canvas>
      </main>
    </div>
  )
}

export default Home
