import React, { Suspense, useState, useEffect, useRef } from 'react'
import Head from 'next/head'

import Typed from 'typed.js'

import { Canvas, useThree } from '@react-three/fiber'
import { OrbitControls, Stage } from '@react-three/drei'

import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'

import Duck from '../components/models/Duck'

import Dialogue from '@/components/Dialogue'
import DialoguesData from '@/data/dialoguesData.json'

import Container from '@/components/Container'

import * as THREE from 'three'

import NET from 'vanta/dist/vanta.net.min'
// Make sure window.THREE is defined, e.g. by including three.min.js in the document head using a <script> tag

const VantaNet = ({ children }) => {
  const [vantaEffect, setVantaEffect] = useState(0)
  const vantaRef = useRef(null)
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(
        NET({
          el: vantaRef.current,
          THREE,
          points: 15,
          color: 0x14b679,
          backgroundColor: 0x222222,
          maxDistance: 10,
        }),
      )
    }
    return () => {
      if (vantaEffect) vantaEffect.destroy()
    }
  }, [vantaEffect])
  return (
    <div className="w-full h-full relative" ref={vantaRef}>
      {children}
    </div>
  )
}

function AnimationWrapper() {
  gsap.registerPlugin(ScrollTrigger)
  const [, forceUpdate] = React.useReducer((x) => x + 1, 0)
  const { scene, camera } = useThree()
  const tl = gsap.timeline({
    scrollTrigger: {
      trigger: '#section-two',
      start: 'top top',
      endTrigger: '#section-five',
      end: 'bottom bottom',
      scrub: 1,
    },
  })

  React.useEffect(() => {
    scene.rotation.set(0, 0, 0)
    camera.position.set(2, 1, 5)

    tl.to(scene.rotation, { y: 4.79 })
      .to(camera.position, { x: -0.1 })
      .to(scene.rotation, { z: 1.6 })
      .to(scene.rotation, { z: 0.02, y: 3.1 }, 'simultaneously')
      .to(camera.position, { x: 0.16 }, 'simultaneously')

    setInterval(() => {
      forceUpdate()
    }, 500)
  }, [])

  return null
}

const Home = () => {
  const duckRef = React.useRef(null)
  const TypedRef = useRef(null)
  const [repoList, setRepoList] = useState([])
  const [dialogueIndex, setDialogueIndex] = useState(0)

  useEffect(() => {
    const typed = new Typed(TypedRef.current, {
      strings: ['Welcome to 1tpp.com', 'print("Panapat Pilapa")'], // Strings to display
      // Speed settings, try diffrent values untill you get good results
      startDelay: 300,
      typeSpeed: 80,
      backSpeed: 20,
      backDelay: 20,
      smartBackspace: true,
      loop: true,
      showCursor: true,
      cursorChar: "|"
    })

    fetch('https://api.github.com/users/1tpp/repos')
      .then((res) => res.json())
      .then((data) => {
        const result = data.filter((repo) => {
          return repo.fork == false
        })

        setRepoList(result)
      })

    return () => {
      typed.destroy()
    }
  }, [])

  const handleOnClick = (event) => {
    event.preventDefault()

    if (dialogueIndex < DialoguesData.length - 1) {
      setDialogueIndex(dialogueIndex + 1)
    } else {
      setDialogueIndex(0)
      return
    }
  }

  return (
    <>
      <Head>
        <title>1tpp | Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VantaNet>
        <Canvas
          camera={{ fov: 65 }}
          style={{
            width: '100vw',
            height: '100vh',
            zIndex: 10,
            position: 'fixed',
            userSelect: 'none',
          }}
        >
          <Suspense fallback={null}>
            <Duck position={[0, 0, 0]} />
            <AnimationWrapper />
            <ambientLight />
            <pointLight position={[10, 10, 10]} />
            {/* <OrbitControls ref={duckRef} /> */}
          </Suspense>
        </Canvas>

        <Container>
          <section id="section-one" className="w-full h-screen flex justify-center items-center relative z-50">
            <div className="text-white">
             <span className="text-5xl" ref={TypedRef}></span>
            </div>
          </section>

          <section id="section-two" className="w-full h-auto relative z-50">
            <div className="flex flex-col items-center justify-center">
              <h3 className="text-2xl font-bold tracking-tight dark:text-white">
                Project on Github
              </h3>
              <div className="space-y-8 flex justify-center items-end flex-row flex-wrap">
                {repoList.map((repo) => (
                  <a key={repo.id} href={`${repo.html_url}`} target="_blank">
                    <div className="p-6 mr-8 max-w-sm h-32 bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                      <h3 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                        {repo.name}
                      </h3>
                      <p className="font-normal text-gray-700 dark:text-gray-400">
                        {repo.description}
                      </p>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          </section>

          <section
            id="section-three"
            className="w-full h-screen relative z-50"
          ></section>
          <section
            id="section-four"
            className="w-full h-screen relative z-50"
          ></section>
          <section
            id="section-five"
            className="w-full h-screen relative z-50"
          ></section>
        </Container>
      </VantaNet>
    </>
  )
}

export default Home
